data_dir: data/grasp_shelf/
logs_dir: logs/${now}  # "now" has to be created in python code

seed: 1006

train_ratio: 0.8
max_epochs: 5000
log_every_n_steps: 1
learning_rate: 0.002
batch_size_train: 12
batch_size_val: 3

early_stopping:
  monitor: val_loss
  patience: 200
  mode: min
mdl_ckpt:
  monitor: val_loss
  mode: min
  dirpath: ${logs_dir}/checkpoints
  # save_top_k: 3
  filename: '{epoch}-{val_loss:.2f}'
  # every_n_train_steps: 2000

wandb:
  project: "amigrasp"
  config: {}
  save_dir: ${logs_dir}
  log_model: true