data_dir: data/grasp_shelf/
logs_dir: logs/${now}  # "now" has to be created in python code

seed: 1006

img_size: 640
max_depth_mm: 700

use_rgb: false
rgb_backbone: resnet18  # resnet18 or smallcnn
freeze_rgb_backbone: false

# No reason for these to change too much
use_depth: true
depth_backbone: resnet18  # resnet18 or smallcnn
freeze_depth_backbone: false

train_ratio: 0.75
max_epochs: 7000
log_every_n_steps: 1
learning_rate: 0.002
batch_size_train: 84
batch_size_val: 42
optimizer: adam  # adam, sgd, adamw

early_stopping:
  monitor: val_loss
  patience: 300
  mode: min
mdl_ckpt:
  monitor: val_loss
  mode: min
  dirpath: ${logs_dir}/checkpoints
  # save_top_k: 3
  filename: '{epoch}-{val_loss:.2f}'
  # every_n_train_steps: 2000

wandb:
  project: "amigrasp"
  config: {}
  save_dir: ${logs_dir}
  log_model: true