script_name: Dev

robot_zmq:
  host: localhost
  port: 5555
  class_name: AMIGA
  async_client: false

cam_zmq:
  host: localhost
  port: 5556
  class_name: ZEDCamera
  async_client: true

yolo_weights: resources/models/250218_yolov11s_datav2_mAP50=0.988.pt
grasp_mdl_ckpt_path: resources/models/250220_grasp_v2_val_loss=0.22.ckpt


# Old ings
# resources/models/241214_grasp_val_loss=0.32.ckpt 
# resources/models/241209_yolov11s_datav6_mAP50=0.918.pt
