FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

SHELL ["/bin/bash", "-c"]

# Group apt updates and installs together
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    git \
    wget \
    vim \
    libhidapi-dev \
    python3-pip \
    android-tools-adb \
    ffmpeg \
    python-is-python3 \
    libxcb-cursor0 \
    libegl1-mesa-dev && \
    rm -rf /var/lib/apt/lists/* 


CMD python 